import type { Metadata } from "next";
import React from "react";
// import { Geist, Geist_Mono, Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider"; 
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
//   display: "swap",
// });

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <AuthProvider>
          <Navbar />
          {children}
          <Toaster />
        </AuthProvider>
    </>
  );
}
